title: DoMax

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate-v2

bookshop_locations:
  - ../component-library

exclude:
  - postcss.config.js
  - node_modules

pagination:
  enabled: true
  per_page: 6
  permalink: '/blog/page/:num/'
  title: ':title - Page :num'
  sort_field: 'date'
  sort_reverse: true

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /project/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

max_index_projects: 3
max_index_blogs: 3
