source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"

gem "csv", "~> 3.3.5"
gem "base64", "~> 0.3.0"
gem "logger", "~> 1.7.0"
gem "bigdecimal", "~> 4.1.2"

group :jekyll_plugins do
  gem "jekyll-bookshop", "~> 3.18.5"
  gem "jekyll-tagging", "~> 1.1.0"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-paginate-v2", "~> 3.0.0"
end
